FROM jupyter/datascience-notebook:latest
RUN pip install openai
# Copy the .whl and .tar.gz files into the Docker image
COPY bearborg_extension-0.1.0-py3-none-any.whl /tmp/
COPY bearborg_extension-0.1.0.tar.gz /tmp/

# Install the JupyterLab extension using pip
RUN pip install -v /tmp/bearborg_extension-0.1.0-py3-none-any.whl \
    && jupyter labextension install --no-build bearborg_extension \
    && jupyter lab build

# Clean up the temporary files
RUN rm /tmp/bearborg_extension-0.1.0-py3-none-any.whl \
    && rm /tmp/bearborg_extension-0.1.0.tar.gz

# Expose the default notebook port
EXPOSE 8888

# Set the default command to start JupyterLab
CMD ["start-notebook.sh"]
